### ISSUE TITLE
Arbitrary profiles don't seem to work

### ISSUE THREAD

**Issue by pboley** [amerand/PMOIRED#3]
Trying to run the example for arbitrary radial profiles causes an error.
Am I doing something wrong?

```python
param = {'diam':1.0, 'profile':'$MU**$alpha', '$alpha':0.1}

data.doFit(param)
```

[dpfit] 2 FITTED parameters: ['$alpha', 'diam']
[dpfit] using scipy.optimize.leastsq
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-44-f118744c21f5>", line 8, in <module>
    data.doFit(param)

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/__init__.py", line 191, in doFit
    self.bestfit = oimodels.fitOI(self._merged, model, fitOnly=fitOnly,

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/oimodels.py", line 1795, in fitOI
    fit = dpfit.leastsqFit(residualsOI, tmp, firstGuess, z, verbose=verbose,

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/dpfit.py", line 361, in leastsqFit
    scipy.optimize.leastsq(_fitFunc, pfit,

  File "/usr/lib/python3/dist-packages/scipy/optimize/minpack.py", line 383, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)

  File "/usr/lib/python3/dist-packages/scipy/optimize/minpack.py", line 26, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/dpfit.py", line 673, in _fitFunc
    model = func(x, params)

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/oimodels.py", line 1615, in residualsOI
    res = np.append(res, residualsOI(o, param, timeit=timeit))

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/oimodels.py", line 1646, in residualsOI
    m = VmodelOI(oi, param, timeit=timeit)

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/oimodels.py", line 884, in VmodelOI
    return VsingleOI(oi, param, imFov=imFov, imPix=imPix, imX=imX, imY=imY,

  File "/home/pboley/.local/lib/python3.8/site-packages/pmoired-0.1.dev0-py3.8.egg/pmoired/oimodels.py", line 423, in VsingleOI
    Ir = eval(tmp)

  File "<string>", line 1
    _mu**$alpha
         ^
SyntaxError: invalid syntax

**Comment by pboley** [comment]
Fixed by https://github.com/amerand/PMOIRED/pull/4/commits/53249419d924f9ec5518b91b900adac4667d64d9

**Comment by amerand** [comment]
Oh I see now... all is good I suppose.
